### PR TITLE
Add keywords popover and search chips

### PR DESCRIPTION
**Pull request by Ron-Lavi**
When hovering a keywords tag, a popover would appear.
When clicking on one of the keywords, the query will be
shown in a chip under the searchbar.

https://user-images.githubusercontent.com/26363699/158600176-be6a4eb4-a7d2-49e1-88c1-8898bbebbe3a.mp4

cc @lzap @ofedoren @marisvirik

### CODE REVIEW

**Comment by Ron-Lavi** [comment]
Still WIP

**Comment by lzap** [comment]
Remember a report can have hundreds of keywords if all steps fail in the worst case, I would probably enforce some limit, or maybe implement a scroll bar.

**Comment by Ron-Lavi** [comment]
@marisvirik any thoughts about a solution for hundreds of keywords, e.g: open Modal/scrollbar?

**Comment by Ron-Lavi** [comment]
Closing for now as we decided to postpone this feature until there's more capacity

**Pull request closed without merging**
