### PR TITLE
adjust package.json

### PR DESCRIPTION
**Pull request by Ron-Lavi**

### CODE REVIEW

**Comment by lzap** [comment]
Please let me know once you figure out with packaging.

**Comment by Ron-Lavi** [comment]
should we do a pre-release to test it in packaging?
@theforeman/packaging, from your experience, any issues using `"*"` in package.json?

**Comment by evgeni** [comment]
`*` is literally "anything", right?

https://github.com/theforeman/foreman-packaging/blob/rpm/develop/update-requirements doesn't support that, but there is no reason we can't teach it.

Out of curiosity, why * and not >= some base version?

**Comment by Ron-Lavi** [comment]
> Out of curiosity, why * and not >= some base version?

Hey @evgeni, I think it's the same but probably with `*` it could bring more freedom to packaging,
for us, it doesn't change much really so let me update my PR with `>=` 🤣

**Comment by evgeni** [comment]
Technically, you can translate `*` to `>= 0`, which I think what RPM does internally when you omit any version modifier.

**Comment by Ron-Lavi** [comment]
> Technically, you can translate `*` to `>= 0`, which I think what RPM does internally when you omit any version modifier.

Nice, trying

**Comment by ofedoren** [comment]
@Ron-Lavi, the tests are green, do we need anything else here or wait for something? :)

**Comment by Ron-Lavi** [comment]
@ofedoren @evgeni what are you two doing here on Sunday? :D
I think we can get it in and try it in packaging already with the next release

**Comment by evgeni** [comment]
I can try running the packing helper tomorrow even without a release, but I see no reason for this not to produce the expected result (an essentially unversioned dependency on builder)

**Review by ofedoren — APPROVED** [review]
Thanks, @Ron-Lavi, merging based on comments.

**Comment by evgeni** [comment]
FTR, this generated exactly the expected result:

```patch
 # start package.json devDependencies BuildRequires
 BuildRequires: %{?scl_prefix}npm(@babel/core) >= 7.7.0
 BuildRequires: %{?scl_prefix}npm(@babel/core) < 8.0.0
-BuildRequires: %{?scl_prefix}npm(@theforeman/builder) >= 10.0.0
-BuildRequires: %{?scl_prefix}npm(@theforeman/builder) < 11.0.0
+BuildRequires: %{?scl_prefix}npm(@theforeman/builder) >= 0
 BuildRequires: %{?scl_prefix}npm(jed) >= 1.1.1
 BuildRequires: %{?scl_prefix}npm(jed) < 2.0.0
 # end package.json devDependencies BuildRequires
```

**Pull request merged**
